# Generated by Django 5.2.1 on 2025-05-18 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('total_sales', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tổng doanh thu')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Tổng đơn hàng')),
                ('total_users', models.PositiveIntegerField(default=0, verbose_name='Tổng người dùng')),
            ],
            options={
                'verbose_name': 'Thống kê',
                'verbose_name_plural': 'Thống kê',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProductStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Lượt xem')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Lượt mua')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Thống kê sản phẩm',
                'verbose_name_plural': 'Thống kê sản phẩm',
                'ordering': ['-date'],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_count', models.PositiveIntegerField(default=0, verbose_name='Số đơn hàng')),
                ('total_spent', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Tổng chi tiêu')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Thống kê người dùng',
                'verbose_name_plural': 'Thống kê người dùng',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
