# Generated by Django 5.2.1 on 2025-05-18 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên thương hiệu')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Thương hiệu',
                'verbose_name_plural': 'Thương hiệu',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhà cung cấp')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Thông tin liên hệ')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Địa chỉ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày nhập')),
                ('total', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tổng tiền')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='accounts.employee', verbose_name='Nhân viên')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='products.supplier', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Phiếu nhập',
                'verbose_name_plural': 'Phiếu nhập',
                'ordering': ['-import_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Hình ảnh')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Số lượng tồn kho')),
                ('available', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('room_type', models.CharField(choices=[('LR', 'Phòng khách'), ('BR', 'Phòng ngủ'), ('KT', 'Nhà bếp'), ('DR', 'Phòng ăn'), ('OF', 'Văn phòng'), ('BT', 'Phòng tắm'), ('OT', 'Khác')], default='LR', max_length=2, verbose_name='Loại phòng')),
                ('material', models.CharField(choices=[('WD', 'Gỗ'), ('MT', 'Kim loại'), ('GL', 'Kính'), ('PL', 'Nhựa'), ('FB', 'Vải'), ('LT', 'Da'), ('OT', 'Khác')], default='WD', max_length=2, verbose_name='Chất liệu')),
                ('dimensions', models.CharField(blank=True, max_length=100, verbose_name='Kích thước (DxRxC cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Trọng lượng (kg)')),
                ('warranty', models.PositiveIntegerField(default=12, verbose_name='Bảo hành (tháng)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Đã xóa')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.brand', verbose_name='Thương hiệu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('import_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='products.import', verbose_name='Phiếu nhập')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_details', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập',
                'verbose_name_plural': 'Chi tiết phiếu nhập',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d', verbose_name='Hình ảnh')),
                ('is_main', models.BooleanField(default=False, verbose_name='Ảnh chính')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'Hình ảnh sản phẩm',
                'verbose_name_plural': 'Hình ảnh sản phẩm',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id', 'slug'], name='products_pr_id_a08e3c_idx'),
        ),
    ]
